- name: Create user
  user:
    name: "{{ user_name }}"
    password: "{{ user_password | password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /bin/zsh
    update_password: on_create

- name: Set authorized key from ~/.ssh/id_ecdsa.pub
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ecdsa.pub') }}"
